scripts:
  - alt-j
  - ax
  - b
  - be
  - browse
  - chooser
  - gd
  - launch
  - note
  - nord
  - opendir
  - pe
  - pm
  # - switch_layout
  - the
  - tmux-status
  - tx
  - yn
  - vp
  - x
  - xtm
  - nc
